name: .NET CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Stop IIS
      run: iisreset /stop

    - name: Copy Files
      run: xcopy /E /Y publish\* C:\inetpub\CICDDemo\

    - name: Start IIS
      run: iisreset /start